version: 2
updates:
- package-ecosystem: npm
  directory: /
  labels: [dependencies]
  reviewers: [Katsute]
  schedule:
    interval: daily
    time: '07:00'
    timezone: US/Eastern
  open-pull-requests-limit: 99